apiVersion: v1
kind: Service
metadata:
  name: appsrv-php
  labels:
    app: appsrv
    role: webserver
    tier: frontend
spec:
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: appsrv
    role: webserver
    tier: frontend
