apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: appsrv
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: load-balancer
    tier: frontend
